### ISSUE TITLE
Make the date offset 2020-01-01, not 1970-01-01

### ISSUE THREAD

**Issue by johnlees** [mrc-ide/sircovid#108]
Would make numeric dates easier to understand

**Comment by richfitz** [comment]
The way I'd suggest doing this is not to actually use an offset at all (so basically don't use date objects for anything other than plotting).  I think that the offset might need to be `2019-12-31` so that day 1 is `2020-01-01`; i.e. we'll work in terms of 2020 Julian day, which is pretty understandable for the rest of this year and we can deal with it later.

```
as.Date(1, origin = "2020-01-01") # oops
lubridate::yday("2020-01-01") # this is better
as.Date(1, origin = "2019-12-31")
```
